<?php
# This file was automatically generated by the MediaWiki 1.25.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "SOCLE";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgScriptExtension = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://smw.learning-socle.org";

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";
$wgResourceBasePath = $wgScriptPath;

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "/images/logo.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@smw.learning-socle.org";
$wgPasswordSender = "apache@smw.learning-socle.org";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "mediawiki";
$wgDBuser = "mediawikiuser";
$wgDBpassword = "pls15";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "C.UTF-8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "fr";

$wgSecretKey = "afee81df81cfccda25c96e504841a228ccfcb7f7cf7a77e733d5649804609441";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "3c615cf2684049ce";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://www.gnu.org/copyleft/fdl.html";
$wgRightsText = "GNU Free Documentation License 1.3 ou ultérieure";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/gnu-fdl.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = true;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['read'] = false;
$wgGroupPermissions['user']['edit'] = true;
$wgGroupPermissions['user']['read'] = true;

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
#$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'CologneBlue' );
wfLoadSkin( 'Modern' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Vector' );


# Enabled Extensions. Most extensions are enabled by including the base extension file here
# but check specific extension documentation for more details
# The following extensions were automatically enabled:
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'ParserFunctions' );


# End of automatically generated settings.
# Add more configuration options below.

#Show Exception Details
$wgShowExceptionDetails = true;

### DISPLAY PHP ERRORS
error_reporting( -1 );
ini_set( 'display_errors', 1 );

enableSemantics('smw.learning-socle.org');

#wfLoadExtension('SemanticGraph');
#wfLoadExtension('SemanticForms');
#wfLoadExtension('SemanticResultFormats');
#wfLoadExtension('Scribunto');
#wfLoadExtension('VisualEditor');

require_once "$IP/extensions/SemanticForms/SemanticForms.php";
#require_once "$IP/extensions/SemanticResultFormats/SemanticResultFormats.php";
require_once "$IP/extensions/Scribunto/Scribunto.php";
require_once "$IP/extensions/VisualEditor/VisualEditor.php";
#require_once "$IP/extensions/ParserFunctions/ParserFunctions.php";
#require_once "$IP/skins/MediaWikiBootstrap/MediaWikiBootstrap.php";
#require_once "$IP/skins/Tweeki/Tweeki.php";
require_once "$IP/skins/apex/apex.php";
require_once "$IP/extensions/WikiEditor/WikiEditor.php";
require_once "$IP/extensions/EmbedVideo/EmbedVideo.php";
require_once "$IP/extensions/GraphViz/GraphViz.php";
require_once "$IP/extensions/SemanticGraph/includes/SemanticGraph2.php";
require_once "$IP/extensions/ImageMap/ImageMap.php";
require_once "$IP/extensions/xyCategoryBrowser/xyCategoryBrowser.php";
require_once "$IP/extensions/PlantUML/PlantUML.php";

$wgDefaultSkin = "apex";
$wgScribuntoDefaultEngine = 'luastandalone';
$wgDefaultUserOptions['visualeditor-enable'] = 1;
$wgHiddenPrefs[] = 'visualeditor-enable';

### Wiki Editor Config
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['sebetatoolbar-cgd'] = 1;
$wgDefaultUserOptions['wikieditor-preview'] = 1;
$wgDefaultUserOptions['wikieditor-publish'] = 1;

### GraphViz Config
$wgGraphVizSettings -> createCategoryPages = "yes";

### SemanticGraph Config
$wgFileExtensions[] = 'mm';
$wgVerifyMimeType = false;

### Visual Editor Config
$wgVisualEditorParsoidURL = 'http://localhost:8142';
$wgVisualEditorParsoidPrefix = 'localhost';
$wgSessionsInObjectCache = true;
$wgVisualEditorParsoidForwardCookies = true;

### SMW FACTBOX
$smwgShowFactbox = SMW_FACTBOX_NONEMPTY;

### ImageMap
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";


### NameSpaces ###
define("NS_GEI", 3000); 
define("NS_GEI_TALK", 3001);
define("NS_GMM", 3002);
define("NS_GMM_TALK", 3003);
define("NS_TEACHER",3004);
define("NS_TEACHER_TALK",3005);

$wgExtraNamespaces[NS_GEI] = "GEI";
$wgExtraNamespaces[NS_GEI_TALK] = "GEI_Talk";
$wgExtraNamespaces[NS_GMM] = "GMM";
$wgExtraNamespaces[NS_GMM_TALK] = "GMM_Talk";
$wgExtraNamespaces[NS_TEACHER] = "TEACHER";
$wgExtraNamespaces[NS_TEACHER_TALK] = "TEACHER_Talk";


